[project]
name = "candidate-challenge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "fastapi[standard]>=0.115.14",
    "python-dateutil>=2.9.0.post0",
    "requests>=2.32.4",
]
